### ISSUE TITLE
Blank height and width attributes

### ISSUE THREAD

**Issue by houseraevan** [factmaven/specify-image-dimensions#2]
**Reference**: [Blank height and width attributes](https://wordpress.org/support/topic/blank-height-and-width-attributes/)

When there are images that have blank dimensions (for both `width` and `height`), the plugin doesn't detect it:

    <img src="https://placehold.it/100x50" width="" height="">

However, when there is only one blank dimension, my plugin does catch it. The following two examples will work:

    <img src="https://placehold.it/100x50" width="">
    <img src="https://placehold.it/100x50" height="">

**Comment by jinksraevan** [comment]
Issue have been resolved since v1.0.4
